import {useMemo,useState} from 'react'
import AdminShell,{SystemIcon} from './AdminShell'
import ManagementOverview from './ManagementOverview'
import './DemoPages.css'

type Employee={id:number;nome:string;cpf:string;funcao:string;status:string;facial:string}
const initialEmployees:Employee[]=[
{id:1,nome:'Lucas Almeida',cpf:'***.482.***-10',funcao:'Auxiliar Logístico',status:'Ativo',facial:'Cadastrado'},
{id:2,nome:'Mariana Costa',cpf:'***.731.***-42',funcao:'Auxiliar Logístico',status:'Ativo',facial:'Cadastrado'},
{id:3,nome:'Rafael Martins',cpf:'***.206.***-55',funcao:'Conferente',status:'Ativo',facial:'Pendente'},
{id:4,nome:'Beatriz Souza',cpf:'***.915.***-03',funcao:'Auxiliar Logístico',status:'Ativo',facial:'Cadastrado'},
{id:5,nome:'Gabriel Rocha',cpf:'***.347.***-88',funcao:'Auxiliar Logístico',status:'Ativo',facial:'Pendente'},
{id:6,nome:'Camila Ribeiro',cpf:'***.604.***-27',funcao:'Líder de Equipe',status:'Ativo',facial:'Cadastrado'}]
const labels:Record<string,string>={operacao:'Operação do Dia',historicoOperacional:'Histórico Operacional',funcionarios:'Funcionários',ponto:'Controle de Ponto',listaDiaristas:'Lista do Dia',diarias:'Diárias',fechamentos:'Fechamentos',pagamentos:'Pagamentos',documentos:'Documentos',epis:'EPIs',relatorios:'Relatórios',calendario:'Calendário',usuarios:'Usuários e Acessos',auditoria:'Auditoria',configuracoes:'Configurações'}
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
function Head({screen,sub,action}:{screen:string,sub:string,action?:React.ReactNode}){return <div className="demo-page-head"><div><span className="demo-eyebrow">{screen==='operacao'?'OPERAÇÃO ATUAL':'GESTÃO SINDICAL'}</span><h1>{labels[screen]}</h1><p>{sub}</p></div>{action}</div>}
function Cards({items}:{items:[string,string,string][]}){return <div className="demo-cards">{items.map(([a,b,c])=><div className="demo-card" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div>}
function Table({heads,children}:{heads:string[],children:React.ReactNode}){return <div className="demo-panel"><div className="table-wrapper"><table className="employees-table"><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div></div>}
function Badge({children,kind='ok'}:{children:React.ReactNode,kind?:string}){return <span className={`demo-badge ${kind}`}>{children}</span>}
export default function DemoApp(){
 const [screen,setScreen]=useState('dashboard'),[workspace,setWorkspace]=useState<'gestao'|'acesso'>('gestao'),[employees,setEmployees]=useState(initialEmployees),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[saved,setSaved]=useState('');
 const flash=(x:string)=>{setNotice(x);setSaved(new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}));setTimeout(()=>setNotice(''),1900)}
 const canAccess=()=>true
 const go=(s:string)=>setScreen(s)
 const today=new Date().toLocaleDateString('pt-BR')
 const content=useMemo(()=>{
  if(screen==='dashboard') return <ManagementOverview name="Administrador Demo" active={18} dailyPending={3} dailyValue="R$ 426,00" paymentsPending={5} paymentsValue="R$ 1.284,50" closing={{periodo:'01 a 15 de outubro',status:'Em andamento',pagamento:'16/10/2026'}} dailyCount={25} forecast="R$ 3.550,00" progress={88} canAccess={()=>true} onNavigate={go} lists={[{data:new Date().toISOString().slice(0,10),local:'Nexus Logística · Mogi Mirim',diaristas:employees.slice(0,5).map(x=>x.nome)}]}/>
  if(screen==='operacao') return <div className="demo-page"><Head screen={screen} sub="Escala, presença, faltas e diárias em uma única visão." action={<><input className="demo-date" type="date" defaultValue="2026-10-05"/><button className="secondary-button" onClick={()=>flash('Lista do Dia aberta para edição')}>Editar Lista do Dia</button></>}/><div className="demo-status-strip"><div><b>Lista do Dia encontrada • 05/10/2026</b><span>5 diaristas escalados para o turno PM.</span></div><Badge>Lista ativa</Badge></div><Cards items={[["Escalados","5","Lista do Dia"],["Presentes","3","Registros confirmados"],["Faltas","1","Lançada"],["Diárias geradas","3","R$ 432,00"]]}/><div className="demo-two"><Table heads={['FUNCIONÁRIO','FUNÇÃO','PRESENÇA','ENTRADA','STATUS']}>{employees.slice(0,5).map((e,i)=><tr key={e.id}><td><b>{e.nome}</b></td><td>{e.funcao}</td><td>{i<3?'Presente':i===3?'Falta':'Aguardando'}</td><td>{i<3?`09:${28+i}`:'—'}</td><td><Badge kind={i<3?'ok':i===3?'bad':'warn'}>{i<3?'Registrado':i===3?'Falta':'Pendente'}</Badge></td></tr>)}</Table><aside className="demo-side-card"><h3>Resumo financeiro</h3><p><span>Diária base</span><b>R$ 100,00</b></p><p><span>Vale-transporte</span><b>R$ 12,00</b></p><p><span>Vale-refeição</span><b>R$ 32,00</b></p><p className="total"><span>Por diarista</span><b>R$ 144,00</b></p><button className="primary-button" onClick={()=>flash('Diárias do dia geradas na demonstração')}>✓ Gerar diárias do dia</button></aside></div></div>
  if(screen==='historicoOperacional') return <div className="demo-page"><Head screen={screen} sub="Consulte as operações realizadas e seus resultados."/><div className="demo-toolbar"><input placeholder="Pesquisar operação..."/><select><option>Todos os períodos</option><option>Outubro/2026</option></select></div><Table heads={['DATA','EMPRESA','TURNO','ESCALADOS','PRESENTES','DIÁRIAS','STATUS']}>{['05/10/2026','04/10/2026','03/10/2026','02/10/2026'].map((d,i)=><tr key={d}><td><b>{d}</b></td><td>Nexus Logística</td><td>PM</td><td>{5+i}</td><td>{4+i}</td><td>{4+i}</td><td><Badge>Concluída</Badge></td></tr>)}</Table></div>
  if(screen==='funcionarios') return <div className="demo-page"><Head screen={screen} sub="Cadastre e gerencie os trabalhadores vinculados à operação." action={<button className="primary-button" onClick={()=>setModal('employee')}>+ Novo funcionário</button>}/><div className="demo-toolbar"><input placeholder="Pesquisar por nome, CPF ou função..."/><span>{employees.length} funcionário(s)</span></div><Table heads={['NOME','CPF','FUNÇÃO','FACIAL','STATUS','AÇÕES']}>{employees.map(e=><tr key={e.id}><td><b>{e.nome}</b></td><td>{e.cpf}</td><td>{e.funcao}</td><td><Badge kind={e.facial==='Cadastrado'?'ok':'warn'}>{e.facial}</Badge></td><td><Badge>{e.status}</Badge></td><td><button className="demo-link" onClick={()=>flash('Cadastro fictício selecionado')}>Editar</button></td></tr>)}</Table></div>
  if(screen==='ponto') return <div className="demo-page"><Head screen={screen} sub="Acompanhe entradas, saídas e registros realizados no terminal." action={<button className="primary-button" onClick={()=>{setWorkspace('acesso');flash('Terminal facial aberto em modo demonstrativo')}}>◉ Abrir Totem</button>}/><Cards items={[["Registros hoje","6","Entradas e saídas"],["Entradas","4","Confirmadas"],["Saídas","2","Confirmadas"],["Pendências","1","Revisão manual"]]}/><Table heads={['FUNCIONÁRIO','FUNÇÃO','DATA','HORÁRIO','MÉTODO','STATUS','AÇÕES']}>{employees.slice(0,5).map((e,i)=><tr key={e.id}><td><b>{e.nome}</b></td><td>{e.funcao}</td><td>{today}</td><td><b>09:{28+i}</b></td><td>{i===2?'Manual':'Facial'} • Entrada</td><td><Badge>Registrado</Badge></td><td><button className="demo-link" onClick={()=>flash('Registro demonstrativo aberto')}>Ver</button></td></tr>)}</Table></div>
  if(screen==='listaDiaristas') return <div className="demo-page"><Head screen={screen} sub="Organize os diaristas escalados para cada operação." action={<button className="primary-button" onClick={()=>flash('Nova lista criada na demonstração')}>+ Nova Lista</button>}/><div className="demo-list-card"><div><span>05 OUT 2026</span><h2>Nexus Logística · Turno PM</h2><p>09:30 às 18:30 · 5 diaristas selecionados</p></div><Badge>Ativa</Badge></div><Table heads={['FUNCIONÁRIO','FUNÇÃO','TRANSPORTE','STATUS']}>{employees.slice(0,5).map(e=><tr key={e.id}><td><b>{e.nome}</b></td><td>{e.funcao}</td><td>Vale-transporte</td><td><Badge>Escalado</Badge></td></tr>)}</Table></div>
  if(screen==='diarias') return <div className="demo-page"><Head screen={screen} sub="Conferência das diárias geradas a partir das operações."/><Cards items={[["Pendentes","3","R$ 426,00"],["Aprovadas","22","R$ 3.124,00"],["Período","01–15 Out","Fechamento atual"],["Total previsto","R$ 3.550,00","25 diárias"]]}/><Table heads={['FUNCIONÁRIO','DATA','BASE','VT','VR','TOTAL','STATUS','AÇÃO']}>{employees.slice(0,5).map((e,i)=><tr key={e.id}><td><b>{e.nome}</b></td><td>0{4+i}/10/2026</td><td>R$ 100,00</td><td>R$ 12,00</td><td>R$ 32,00</td><td><b>R$ 144,00</b></td><td><Badge kind={i<2?'warn':'ok'}>{i<2?'Em conferência':'Aprovada'}</Badge></td><td><button className="demo-link" onClick={()=>flash('Diária aprovada na demonstração')}>Aprovar</button></td></tr>)}</Table></div>
  if(screen==='fechamentos') return <div className="demo-page"><Head screen={screen} sub="Consolide diárias e aprove o período para pagamento." action={<button className="primary-button" onClick={()=>flash('Fechamento demonstrativo processado')}>Novo fechamento</button>}/><Cards items={[["Período atual","01–15 Out","Em andamento"],["Diárias aprovadas","22","R$ 3.124,00"],["Pendências","3","R$ 426,00"],["Total previsto","R$ 3.550,00","Pagamento 16/10"]]}/><div className="demo-list-card"><div><span>FECHAMENTO QUINZENAL</span><h2>01 a 15 de outubro</h2><p>22 aprovadas · 3 pendentes · Pagamento previsto em 16/10/2026</p></div><button className="secondary-button" onClick={()=>flash('Resumo do fechamento aberto')}>Conferir fechamento →</button></div></div>
  if(screen==='pagamentos') return <div className="demo-page"><Head screen={screen} sub="Acompanhe e confirme os repasses do período."/><Cards items={[["Aguardando","5","R$ 1.284,50"],["Pagos","17","R$ 2.415,50"],["Total","22","R$ 3.700,00"],["Método principal","PIX","100% digital"]]}/><Table heads={['BENEFICIÁRIO','REFERÊNCIA','VALOR','CHAVE PIX','STATUS','AÇÃO']}>{employees.slice(0,5).map((e,i)=><tr key={e.id}><td><b>{e.nome}</b></td><td>1ª quinzena/out</td><td><b>{money(i%2?288:432)}</b></td><td>***.***.***-{10+i}</td><td><Badge kind={i<2?'warn':'ok'}>{i<2?'Aguardando':'Pago'}</Badge></td><td><button className="demo-link" onClick={()=>flash('QR PIX demonstrativo aberto')}>Ver PIX</button></td></tr>)}</Table></div>
  if(screen==='documentos') return <div className="demo-page"><Head screen={screen} sub="Centralize documentos e termos da operação." action={<button className="primary-button" onClick={()=>flash('Upload simulado — nenhum arquivo foi enviado')}>+ Adicionar documento</button>}/><Table heads={['DOCUMENTO','CATEGORIA','ATUALIZAÇÃO','STATUS','AÇÃO']}>{[['Termo de ciência — ponto facial','Termos'],['Relatório operacional — Setembro','Relatórios'],['Modelo de lista operacional','Modelos']].map((x,i)=><tr key={i}><td><b>{x[0]}</b></td><td>{x[1]}</td><td>0{2+i}/10/2026</td><td><Badge>Disponível</Badge></td><td><button className="demo-link" onClick={()=>flash('Prévia demonstrativa')}>Visualizar</button></td></tr>)}</Table></div>
  if(screen==='epis') return <div className="demo-page"><Head screen={screen} sub="Controle de entrega e devolução de equipamentos." action={<button className="primary-button" onClick={()=>flash('Entrega de EPI registrada na demonstração')}>Registrar entrega</button>}/><Cards items={[["Entregas no mês","14","Outubro"],["Pendências","2","Assinatura"],["Itens ativos","31","Em posse"]]}/><Table heads={['FUNCIONÁRIO','EPI','QTD.','ENTREGA','ASSINATURA','STATUS']}>{employees.slice(0,4).map((e,i)=><tr key={e.id}><td><b>{e.nome}</b></td><td>{i%2?'Luva de proteção':'Colete refletivo'}</td><td>{i%2?2:1}</td><td>0{1+i}/10/2026</td><td>{i<3?'Confirmada':'Pendente'}</td><td><Badge kind={i<3?'ok':'warn'}>{i<3?'Entregue':'Pendente'}</Badge></td></tr>)}</Table></div>
  if(screen==='relatorios') return <div className="demo-page"><Head screen={screen} sub="Indicadores e consolidação da operação." action={<button className="secondary-button" onClick={()=>flash('Relatório fictício exportado')}>Exportar relatório</button>}/><Cards items={[["Presença média","94%","Últimos 30 dias"],["Diárias geradas","47","No mês"],["Valor consolidado","R$ 6.674,00","No mês"],["Operações","18","Concluídas"]]}/><div className="demo-panel demo-chart"><h3>Diárias por semana</h3>{[72,88,64,95].map((x,i)=><div className="demo-bar" key={i}><span>Semana {i+1}</span><i style={{width:x+'%'}}/><b>{[11,14,9,13][i]}</b></div>)}</div></div>
  if(screen==='calendario') return <div className="demo-page"><Head screen={screen} sub="Visualize operações, fechamentos e pagamentos programados."/><div className="demo-calendar">{Array.from({length:31},(_,i)=><div className="demo-day" key={i}><b>{i+1}</b>{[5,10,15,16,20].includes(i+1)&&<span>{i+1===15?'Fechamento':i+1===16?'Pagamento':'Operação PM'}</span>}</div>)}</div></div>
  if(screen==='usuarios') return <div className="demo-page"><Head screen={screen} sub="Controle quem entra no sistema, níveis de acesso e segurança das contas." action={<button className="primary-button" onClick={()=>flash('Novo usuário demonstrativo')}>+ Novo usuário</button>}/><Cards items={[["Usuários ativos","3","3 cadastrados"],["Administradores","1","Acesso completo"],["Supervisores","1","Acesso operacional"],["Financeiro","1","Acesso financeiro"]]}/><Table heads={['USUÁRIO','PERFIL','EMPRESA','ESCOPO','STATUS','AÇÃO']}>{[['Administrador Demo','Administrador','Todas','Completo'],['Fernanda Lima','Financeiro','Nexus Logística','Financeiro'],['Carlos Mendes','Supervisor','Nexus Logística','Operação']].map((u,i)=><tr key={i}><td><b>{u[0]}</b></td><td>{u[1]}</td><td>{u[2]}</td><td>{u[3]}</td><td><Badge>Ativo</Badge></td><td><button className="demo-link" onClick={()=>flash('Permissões demonstrativas abertas')}>Gerenciar</button></td></tr>)}</Table></div>
  if(screen==='auditoria') return <div className="demo-page"><Head screen={screen} sub="Histórico somente leitura das ações realizadas no sistema."/><Table heads={['DATA/HORA','USUÁRIO','AÇÃO','MÓDULO','NÍVEL']}>{[['05/10/2026 10:20','Administrador Demo','Lista do Dia atualizada','Operação','Informativo'],['05/10/2026 10:12','Fernanda Lima','Pagamento confirmado','Pagamentos','Atenção'],['05/10/2026 09:34','Carlos Mendes','Ponto manual registrado','Ponto','Atenção']].map((a,i)=><tr key={i}><td>{a[0]}</td><td><b>{a[1]}</b></td><td>{a[2]}</td><td>{a[3]}</td><td><Badge kind={i?'warn':'ok'}>{a[4]}</Badge></td></tr>)}</Table><div className="demo-security">⛨ Ambiente de demonstração. Nenhum evento é enviado ao servidor de produção.</div></div>
  if(screen==='configuracoes') return <div className="demo-page"><Head screen={screen} sub="Regras operacionais e valores utilizados no cálculo das diárias."/><div className="demo-settings"><section><h3>Valores da operação</h3><label>Diária base<input defaultValue="100,00"/></label><label>Vale-transporte<input defaultValue="12,00"/></label><label>Vale-refeição<input defaultValue="32,00"/></label><button className="primary-button" onClick={()=>flash('Configurações salvas somente nesta demonstração')}>Salvar alterações</button></section><section><h3>Horários padrão</h3><label>Entrada<input type="time" defaultValue="09:30"/></label><label>Saída<input type="time" defaultValue="18:30"/></label><label>Turno<select><option>PM</option><option>AM</option></select></label></section></div></div>
  return null
 },[screen,employees,workspace])
 function addEmployee(e:React.FormEvent<HTMLFormElement>){e.preventDefault();let f=new FormData(e.currentTarget);setEmployees(v=>[...v,{id:Date.now(),nome:String(f.get('nome')),cpf:'***.000.***-00',funcao:String(f.get('funcao')),status:'Ativo',facial:'Pendente'}]);setModal('');flash('Funcionário fictício cadastrado')}
 return <><div className="demo-banner">AMBIENTE DEMONSTRATIVO · DADOS 100% FICTÍCIOS · SEM CONEXÃO COM O BANCO DE PRODUÇÃO</div><AdminShell current={screen} userName="Administrador Demo" role="Administrador Geral" canAccess={canAccess} onNavigate={go} onSignOut={()=>flash('Saída desativada na demonstração')} onPassword={()=>flash('Alteração de senha desativada na demonstração')} onTerminal={()=>{setWorkspace('acesso');setScreen('ponto');flash('Terminal facial em modo demonstrativo')}} canEdit={true} savedAt={saved} readOnly={false} workspace={workspace} onWorkspace={w=>{setWorkspace(w);setScreen('dashboard')}}>{content}</AdminShell>{notice&&<div className="demo-toast">{notice}</div>}{modal==='employee'&&<div className="demo-modal-back"><form className="demo-modal" onSubmit={addEmployee}><h2>Novo funcionário</h2><p>Cadastro fictício para demonstração pública.</p><label>Nome<input name="nome" required defaultValue="João Demo"/></label><label>Função<select name="funcao"><option>Auxiliar Logístico</option><option>Conferente</option><option>Líder de Equipe</option></select></label><div><button type="button" className="secondary-button" onClick={()=>setModal('')}>Cancelar</button><button className="primary-button">Salvar funcionário</button></div></form></div>}</>
}
