import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import './App.css'
import './Premium.css'
import './Product.css'
import './ModulePolish.css'
import './Refinement.css'
import DemoApp from './DemoApp'
createRoot(document.getElementById('root')!).render(<StrictMode><DemoApp/></StrictMode>)
